import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className='flex gap-4 justify-center items-center mb-5'>
            <Link
              href='/'
              className='btn btn-ghost'
            >
              Home
            </Link>
            <Link
              href='/admin'
              className='btn btn-ghost'
            >
              Admin
            </Link>
            <Link
              href='/users'
              className='btn btn-ghost'
            >
              Users
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
